---
- name: 'configuration play.'
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_host_key_checking: false
    ansible_stdout_callback: yaml

  pre_tasks:
    - name: 'wait 600 seconds for target connection to become reachable/usable.'
      # Your code here
      wait_for_connection:
        timeout: 600

    - name: 'install python for Ansible.'
      become: true
      apt:
        name: python3
        update_cache: yes

  # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    - NODE_ENV: production
    - VERSION: '1'
    - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    - TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR') }}"
    - TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES') }}"
    - TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS') }}"
    - TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    - TYPEORM_PORT: 5432    
    # - TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    - TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    - TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    - TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
    # Add more env vars here

  roles:
    - configure-server
    # - configure-prometheus-node-exporter
