---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: 'wait 600 seconds for target connection to become reachable/usable.'
      wait_for_connection:
        timeout: 600

    - name: "update and upgrade packages"
      shell: |
        sudo apt upgrade -y
        sudo apt-get update -y
        sudo apt autoremove

    # - name: update and upgrade packages  # sudo apt upgrade
    #   become: yes
    #   apt:
    #     upgrade: yes
    #     update_cache: yes
    #     cache_valid_time: 86400

    # - name: remove dependences that are not needed  # sudo apt autoremove
    #   become: yes
    #   apt:
    #     autoremove: yes

  roles:
    - configure-prometheus-node-exporter