---
  - name: "Update"
    become: yes
    apt:
      update_cache: yes
      cache_valid_time: 86400
  
  - name: "delete outdated dependencies"
    become: yes
    apt:
      autoremove: yes

  - name: "upgrade packages"
    become: yes
    apt: 
      upgrade: yes

  - name: "Unarchive build artifact"
    become: yes
    unarchive:
      src: "files/artifact.tar.gz"
      dest: .

  - name: "Start application"
    become: yes
    shell: |
      npm install
      pm2 stop default
      pm2 start npm -- start