global:
  scrape_interval: 15s
  evaluation_interval: 1s

rule_files:
  - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['ec2-54-227-98-87.compute-1.amazonaws.com:9100']      
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['localhost:9093']
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: 
        secret_key: 
        port: 9100