---

- name: "install alert manager"
  unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-0.21.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: "move alertmanager binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/alertmanager-0.21.0.linux-amd64/alertmanager
    dest: /usr/local/bin/alertmanager
    remote_src: yes
    mode: '0777'

- name: "move amtool binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/alertmanager-0.21.0.linux-amd64/amtool
    dest: /usr/local/bin/amtool
    remote_src: yes
    mode: '0777'

- name: "create alertmanager lib directory"
  become: true
  file:
    path: /var/lib/alertmanager
    state: directory

- name: "create/update prometheus.yml file"
  become: true
  copy:
    src: roles/configure-alertmanager/files/prometheus.yml
    dest: /etc/prometheus/prometheus.yml

- name: "copy rules.yml to prometheus config folder"
  become: true
  copy:
    src: roles/configure-alertmanager/files/rules.yml
    dest: /etc/prometheus/rules.yml

- name: "copy alertmanager.yml to /etc/prometheus config folder"
  become: true
  copy:
    src: roles/configure-alertmanager/files/alertmanager.yml
    dest: /etc/prometheus/alertmanager.yml

- name: "add alertmanager service configuration."
  become: true
  copy:
    src: roles/configure-alertmanager/files/alertmanager.service
    dest: /etc/systemd/system/alertmanager.service

- name: 'Change permissions of directories, files and Binaries for Prometheus'
  shell: |
    sudo chown prometheus:prometheus /etc/prometheus
    sudo chown prometheus:prometheus /usr/local/bin/prometheus
    sudo chown prometheus:prometheus /usr/local/bin/promtool
    sudo chown -R prometheus:prometheus /etc/prometheus/consoles
    sudo chown -R prometheus:prometheus /etc/prometheus/console_libraries
    sudo chown -R prometheus:prometheus /var/lib/prometheus

- name: "enable prometheus service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: prometheus
    enabled: yes

- name: "enable alertmanager service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: alertmanager
    enabled: yes


